testsuite: Update pretty_print and add --timeout to runtests.py
runtests.py:
* Changed to re-open stdout in single line buffered mode.
* Changed to print total number of tests that will be run before actually
  running any tests.  This allows_pretty print to tell you where in the
  test run you are.
* Changed to add a '--timeout n' parameter.  If a test fails to output anything
  within n seconds, the test is aborted.  The default is inf so without the
  parameter the behavior is the same as today.  If  the test does timeout, 
  the status printed will be 'timedout' instead of 'passed' or 'failed'.

pretty-print:
* Changed back to filter.   
  Run with ./runtests.py <options> | contrib/scripts/pretty_print
* Added time current test has been running.
* Added total run time to final summary.
* Added 'timedout' to the possible statuses.



git-svn-id: https://origsvn.digium.com/svn/testsuite/asterisk/trunk@5956 a5964663-950a-4945-9369-5dd0b5cb08c1

diff --git a/contrib/scripts/pretty_print b/contrib/scripts/pretty_print
--- a/contrib/scripts/pretty_print
+++ b/contrib/scripts/pretty_print
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Copyright (C) 2014, Fairview 5 Engineering, LLC
 # George Joseph <george.joseph@fairview5.com>
@@ -6,34 +6,74 @@
 # This program is free software, distributed under the terms of
 # the GNU General Public License Version 2.
 #
+
 if [ -t 0 ] ; then
 	echo "pretty_print is a filter and needs the output of runtests.py piped to it."
-	echo "Try python -u ./runtests.py <options> | ./pretty_print"
-	echo "The 'python -u' is needed to use unbuffered output mode otherwise you'll only see output in big chunks."
+	echo "Try ./runtests.py <options> | $0"
 	exit 1
 fi
 
+declare -ix runnable=0
+declare -ix total=0
 declare -ix passed=0
 declare -ix failed=0
+declare -ix timedout=0
 declare -ix tests=0
+declare -ix maxelapsed=0
 declare -a failures
+declare -a timeouts
+declare -ix test_timeout=0
+YELLOW='\033[01;33m'
 GREEN='\033[01;32m'
 RED='\033[01;31m'
 NORM='\033[m'
 
-col=$(( $(tput cols) - 28 ))
+col=$(( $(tput cols) - 36 ))
 
-trap break INT
+counter() {
+	s=1
+	status=Running
+	while(true) ; do
+		sleep 1
+		if [ $test_timeout -gt 0 -a $s -gt $(( ($test_timeout / 4) * 3 )) ] ; then
+			printf "${YELLOW}[%12s %3ss ]${NORM}" "Hung in" $(( $test_timeout - s ))
+		else
+			printf "[%12s %3ss ]" "Running for" $s
+		fi
+		(( s++ ))
+		tput cub 20
+	done
+}
+
+echo -e -n "Calculating...\r"
+
+trap 'kill $countpid &>/dev/null' INT ERR
 while read line ; do
-	if [[ $line =~ ^Running\ tests\ for.* ]] ; then
-		echo $line
-		printf "%-*.*s %4s/${GREEN}%4s${NORM}/${RED}%4s${NORM} ${COLOR} [ %s ]${NORM}\n" $col $col "Test" "Run" "Pass" "Fail" "Status"
+	if [[ $line =~ ^Running.tests.for.(Asterisk.*) ]] ; then
+		version=${BASH_REMATCH[1]}
+		starttime=$SECONDS
 	fi
-	if [[ $line =~ ^Test.*(tests[^\']+)\',.*(passed|failed)$ ]] ; then
+
+	if [[ $line =~ ^Tests.to.run:.([0-9]+),[\ ]+Maximum.test.inactivity.time:.([0-9-]+) ]] ; then
+		runnable=${BASH_REMATCH[1]}
+		export test_timeout=${BASH_REMATCH[2]}
+		echo ${line/-1/unlimited}
+		printf "[%-*.*s ][%-11s][%s][${GREEN}%4s${NORM}][${RED}%4s${NORM}]\n" $col $col "Test" "   Test" "Status" "Pass" "Fail"
+	fi
+
+	if [[ $line =~ ^--\>.Running.test.\'(.+)\'.\.\.\. ]] ; then
+		(( tests++ ))
+		printf "[%-*.*s ][%4d of %3d]" $col $col ${BASH_REMATCH[1]#*/} $tests $runnable
+		st=$SECONDS
+		counter &
+		disown $!
+		countpid=$!
+	fi
+
+	if [[ $line =~ ^Test.*tests/([^\']+)\',.*(passed|failed|timedout)$ ]] ; then
 		test=${BASH_REMATCH[1]}
 		status=${BASH_REMATCH[2]}
-		col=$(( $(tput cols) - 28 ))
-		(( tests++ ))
+		col=$(( $(tput cols) - 36 ))
 		if [[ $status = passed ]] ; then
 			(( passed++ ))
 			COLOR=${GREEN}
@@ -45,12 +85,34 @@ while read line ; do
 			label=Failed
 			failures+=("FAILED: $test")
 		fi
-		printf "%-*.*s %4d/${GREEN}%4d${NORM}/${RED}%4d${NORM} ${COLOR} [ %s ]${NORM}\n" $col $col $test $tests $passed $failed $label
+		if [[ $status = timedout ]] ; then
+			(( failed++ ))
+			(( timedout++ ))
+			COLOR=${RED}
+			label=Hung!!
+			timeouts+=("TIMEDOUT: $test")
+		fi
+		kill $countpid
+		et=$(( $SECONDS - $st ))
+		[[ $et -gt $maxelapsed ]] && maxelapsed=$et
+		printf "[${COLOR}%s${NORM}][${GREEN}%4d${NORM}][${RED}%4d${NORM}]\n" $label $passed $failed
 	fi
 done
-trap - INT
-echo -e "\tTests: $tests\t\t${GREEN}Passed: $passed\t\t${RED}Failed: $failed${NORM}"
+
+trap - INT ERR
+
+kill $countpid &>/dev/null
+
 for fail in "${failures[@]}" ; do
 	echo -e "${RED}$fail${NORM}"
 done
+for to in "${timeouts[@]}" ; do
+	echo -e "${YELLOW}$to${NORM}"
+done
+
+elapsed=$(( $SECONDS - $starttime ))
+time="$(( $elapsed / 60 ))m $(( $elapsed % 60 ))s"
+echo -e "Tests: $runnable   ${GREEN}Passed: $passed   ${RED}Failed: $failed   TimedOut: $timedout${NORM}   Time: $time\tLongest test: ${maxelapsed}s"
+
+
 
