.github Bring workflows up to date with Asterisk

diff --git a/.github/workflows/PROpenedOrUpdated.yml b/.github/workflows/PROpenedOrUpdated.yml
--- a/.github/workflows/PROpenedOrUpdated.yml
+++ b/.github/workflows/PROpenedOrUpdated.yml
@@ -5,23 +5,74 @@ on:
   pull_request_target:
     types: [opened, reopened, synchronize]
 
-#concurrency:
-#  group: ${{github.workflow}}-${{github.event.number}}
-#  cancel-in-progress: true
-
 env:
   ASTERISK_REPO:     ${{vars.ASTERISK_REPO}}
   TESTSUITE_REPO:    ${{github.repository}}
   PR_NUMBER:         ${{github.event.number}}
+  PR_COMMIT:         ${{github.event.pull_request.head.sha}}
   BRANCH:            ${{github.event.pull_request.base.ref}}
   GITHUB_TOKEN:      ${{secrets.GITHUB_TOKEN}}
   MODULES_BLACKLIST: ${{vars.GATETEST_MODULES_BLACKLIST}} ${{vars.UNITTEST_MODULES_BLACKLIST}}
 
 jobs:
-  UnitTests:
+
+  PROpenUpdateUnitTests:
     runs-on: ubuntu-latest
     steps:
-      - name: Run Unit Tests for branch ${{matrix.branch}}
+      - name: Get Token needed to add reviewers
+        if: github.event.action == 'opened'
+        id: get_workflow_token
+        uses: peter-murray/workflow-application-token-action@v1
+        with:
+          application_id: ${{secrets.ASTERISK_ORG_ACCESS_APP_ID}}
+          application_private_key: ${{secrets.ASTERISK_ORG_ACCESS_APP_PRIV_KEY}}
+          organization: asterisk
+
+      - name: Add cherry-pick reminder and reviewers
+        if: github.event.action == 'opened'
+        env:
+          GITHUB_TOKEN: ${{steps.get_workflow_token.outputs.token}}
+          GH_TOKEN: ${{steps.get_workflow_token.outputs.token}}
+          CHERRY_PICK_REMINDER: ${{vars.CHERRY_PICK_REMINDER}}
+          REVIEWERS: ${{vars.PR_REVIEWERS}}
+        run: |
+          IFS=$'; \n'
+          for r in $REVIEWERS ; do
+            echo "Adding reviewer $r"
+            gh pr edit --repo ${{github.repository}} ${PR_NUMBER} --add-reviewer $r || :
+          done
+          # If there's already a reminder comment, don't add another one.
+          ADD_COMMENT=true
+          # This query will FAIL if it finds the comment.
+          gh pr view --repo ${{github.repository}} --json comments \
+            --jq '.comments[].body | select(. | startswith("<!--CPR-->")) | halt_error(1)' \
+            ${{env.PR_NUMBER}} >/dev/null 2>&1 || ADD_COMMENT=false
+          if $ADD_COMMENT ; then
+            echo "Adding CPR comment"
+            gh pr comment --repo ${{github.repository}} \
+              -b "${CHERRY_PICK_REMINDER}" ${{env.PR_NUMBER}}
+          else
+            echo "CPR comment already present"
+          fi
+
+      - name: Set Labels
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh pr edit --repo ${{github.repository}} \
+            --remove-label ${{vars.TEST_CHECKS_PASSED_LABEL}} \
+            --remove-label ${{vars.TEST_CHECKS_FAILED_LABEL}} \
+            --remove-label ${{vars.TEST_GATES_PASSED_LABEL}} \
+            --remove-label ${{vars.TEST_GATES_FAILED_LABEL}} \
+            --remove-label ${{vars.CHERRY_PICK_CHECKS_PASSED_LABEL}} \
+            --remove-label ${{vars.CHERRY_PICK_CHECKS_FAILED_LABEL}} \
+            --remove-label ${{vars.CHERRY_PICK_GATES_PASSED_LABEL}} \
+            --remove-label ${{vars.CHERRY_PICK_GATES_FAILED_LABEL}} \
+            --add-label ${{vars.TESTING_IN_PROGRESS}} \
+            ${{env.PR_NUMBER}} || :
+
+      - name: Run Unit Tests
+        id: rununittests
         uses: asterisk/asterisk-ci-actions/TestsuiteUnitComposite@main
         with:
           asterisk_repo:     ${{env.ASTERISK_REPO}}
@@ -32,24 +83,36 @@ jobs:
           github_token:      ${{secrets.GITHUB_TOKEN}}
           unittest_command:  ${{vars.UNITTEST_COMMAND}}
 
-      - name: Get Token needed to add reviewers
-        id: get_workflow_token
-        uses: peter-murray/workflow-application-token-action@v1
-        with:
-          application_id: ${{secrets.ASTERISK_ORG_ACCESS_APP_ID}}
-          application_private_key: ${{secrets.ASTERISK_ORG_ACCESS_APP_PRIV_KEY}}
-          organization: asterisk
-
-      - name: Add Reviewers
+      - name: Add Checks Passed Label
         if: ${{ success() }}
         env:
-          GITHUB_TOKEN: ${{steps.get_workflow_token.outputs.token}}
-          GH_TOKEN: ${{steps.get_workflow_token.outputs.token}}
-          REVIEWERS: ${{vars.PR_REVIEWERS}}
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          echo "${{env.GITHUB_ACTION}} Add reviewers"
-          IFS=$'; \n'
-          for r in $REVIEWERS ; do
-            gh pr edit --repo ${TESTSUITE_REPO} ${PR_NUMBER} --add-reviewer $r
-          done
+          gh pr edit --repo ${{github.repository}} \
+            --add-label ${{vars.TEST_CHECKS_PASSED_LABEL}} \
+            ${{env.PR_NUMBER}} || :
 
+      - name: Publish Result
+        if: always()
+        env:
+          RESULT:    ${{ steps.rununittests.outcome }}
+          GH_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          gh pr edit --repo ${{github.repository}} \
+            --remove-label ${{vars.TESTING_IN_PROGRESS}} \
+            ${{env.PR_NUMBER}} || :
+        
+          case $RESULT in
+            success)
+              gh pr edit --repo ${{github.repository}} \
+                --add-label ${{vars.TEST_CHECKS_PASSED_LABEL}} \
+                ${{env.PR_NUMBER}} || :
+              exit 0
+              ;;
+            *)
+              gh pr edit --repo ${{github.repository}} \
+                --add-label ${{vars.TEST_CHECKS_FAILED_LABEL}} \
+                ${{env.PR_NUMBER}} || :
+              exit 1
+              ;;
+          esac
